// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressEnc(arg1) {
  return window['go']['main']['App']['CompressEnc'](arg1);
}

export function DecompressEnc(arg1) {
  return window['go']['main']['App']['DecompressEnc'](arg1);
}

export function OpenEnc() {
  return window['go']['main']['App']['OpenEnc']();
}
