// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseApp():Promise<void>;

export function CompressEnc(arg1:main.Xor):Promise<string>;

export function DecompressEnc(arg1:main.Xor):Promise<string>;

export function OpenEnc():Promise<string>;
