# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: wails build -platform=windows/amd64

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Upload Build
        path: ${{env.SOLUTION_FILE_PATH}}build\windows\Launcher.exe
